import { Continent, Country } from '@/types';

// Country list: canonical name, ISO alpha-3, ISO numeric (for map), aliases, and continent.
// Aliases include: alternate names, common misspellings, abbreviations, other languages.
// isoN of -1 means the country isn't in the world-atlas 110m topojson (still tracked in game).
// Continent 'North America' = North + Central America; 'South America' = South America + Caribbean.
export const countries: Country[] = [
  // ─── Africa ───────────────────────────────────────────────────────────────
  { name: 'Algeria', iso3: 'DZA', isoN: 12, continent: 'Africa', aliases: ['algerie', 'algérie', 'algieria', 'algaria'] },
  { name: 'Angola', iso3: 'AGO', isoN: 24, continent: 'Africa', aliases: ['angolа'] },
  { name: 'Benin', iso3: 'BEN', isoN: 204, continent: 'Africa', aliases: ['bénin', 'benin republic', 'dahomey'] },
  { name: 'Botswana', iso3: 'BWA', isoN: 72, continent: 'Africa', aliases: ['bechuanaland'] },
  { name: 'Burkina Faso', iso3: 'BFA', isoN: 854, continent: 'Africa', aliases: ['burkina', 'upper volta', 'burkinafaso'] },
  { name: 'Burundi', iso3: 'BDI', isoN: 108, continent: 'Africa', aliases: [] },
  { name: 'Cabo Verde', iso3: 'CPV', isoN: 132, continent: 'Africa', aliases: ['cape verde', 'cap verde', 'capeverde'] },
  { name: 'Cameroon', iso3: 'CMR', isoN: 120, continent: 'Africa', aliases: ['cameroun', 'camroon', 'cameroun'] },
  { name: 'Central African Republic', iso3: 'CAF', isoN: 140, continent: 'Africa', aliases: ['car', 'central africa', 'c.a.r.', 'centrafrique'] },
  { name: 'Chad', iso3: 'TCD', isoN: 148, continent: 'Africa', aliases: ['tchad'] },
  { name: 'Comoros', iso3: 'COM', isoN: 174, continent: 'Africa', aliases: ['comores', 'comorros', 'comoras'] },
  { name: 'Congo', iso3: 'COG', isoN: 178, continent: 'Africa', aliases: ['republic of congo', 'republic of the congo', 'congo-brazzaville', 'congo republic', 'congo brazzaville'] },
  { name: 'Democratic Republic of the Congo', iso3: 'COD', isoN: 180, continent: 'Africa', aliases: ['drc', 'dr congo', 'congo-kinshasa', 'congo kinshasa', 'zaire', 'droc', 'democratic republic of congo'] },
  { name: "Cote d'Ivoire", iso3: 'CIV', isoN: 384, continent: 'Africa', aliases: ['ivory coast', "côte d'ivoire", 'cote divoire', 'cote d ivoire', 'ivorycoast'] },
  { name: 'Djibouti', iso3: 'DJI', isoN: 262, continent: 'Africa', aliases: ['djibouti republic', 'djibuti', 'jibuti'] },
  { name: 'Egypt', iso3: 'EGY', isoN: 818, continent: 'Africa', aliases: ['egyptian', 'misr', 'egyp'] },
  { name: 'Equatorial Guinea', iso3: 'GNQ', isoN: 226, continent: 'Africa', aliases: ['eq guinea', 'equatorial guinee', 'guinea ecuatorial'] },
  { name: 'Eritrea', iso3: 'ERI', isoN: 232, continent: 'Africa', aliases: ['eritreia', 'eretria'] },
  { name: 'Eswatini', iso3: 'SWZ', isoN: 748, continent: 'Africa', aliases: ['swaziland', 'eswatini kingdom', 'swazilend'] },
  { name: 'Ethiopia', iso3: 'ETH', isoN: 231, continent: 'Africa', aliases: ['abyssinia', 'ethiopa', 'ethopia'] },
  { name: 'Gabon', iso3: 'GAB', isoN: 266, continent: 'Africa', aliases: ['gabun'] },
  { name: 'Gambia', iso3: 'GMB', isoN: 270, continent: 'Africa', aliases: ['the gambia', 'gambia republic'] },
  { name: 'Ghana', iso3: 'GHA', isoN: 288, continent: 'Africa', aliases: ['ghana republic', 'gold coast'] },
  { name: 'Guinea', iso3: 'GIN', isoN: 324, continent: 'Africa', aliases: ['guinea republic', 'guinea conakry'] },
  { name: 'Guinea-Bissau', iso3: 'GNB', isoN: 624, continent: 'Africa', aliases: ['guinea bissau', 'guine-bissau', 'guinea bisau'] },
  { name: 'Kenya', iso3: 'KEN', isoN: 404, continent: 'Africa', aliases: ['kenia', 'kenya republic'] },
  { name: 'Lesotho', iso3: 'LSO', isoN: 426, continent: 'Africa', aliases: ['lesotho kingdom', 'basutoland'] },
  { name: 'Liberia', iso3: 'LBR', isoN: 430, continent: 'Africa', aliases: ['liberia republic'] },
  { name: 'Libya', iso3: 'LBY', isoN: 434, continent: 'Africa', aliases: ['lybia', 'libia', 'lybya'] },
  { name: 'Madagascar', iso3: 'MDG', isoN: 450, continent: 'Africa', aliases: ['malagasy', 'madagaskar', 'madagascaer'] },
  { name: 'Malawi', iso3: 'MWI', isoN: 454, continent: 'Africa', aliases: ['nyasaland', 'malaŵi'] },
  { name: 'Mali', iso3: 'MLI', isoN: 466, continent: 'Africa', aliases: ['mali republic', 'republic of mali'] },
  { name: 'Mauritania', iso3: 'MRT', isoN: 478, continent: 'Africa', aliases: ['mauritanie', 'mauritanea'] },
  { name: 'Mauritius', iso3: 'MUS', isoN: 480, continent: 'Africa', aliases: ['isle of mauritius', 'mauricio'] },
  { name: 'Morocco', iso3: 'MAR', isoN: 504, continent: 'Africa', aliases: ['marocco', 'maroc', 'marruecos', 'morrocco', 'morroco', 'moroco', 'western sahara', 'western sahara territory', 'sahara', 'sahrawi'] },
  { name: 'Mozambique', iso3: 'MOZ', isoN: 508, continent: 'Africa', aliases: ['mocambique', 'moçambique', 'mozambik'] },
  { name: 'Namibia', iso3: 'NAM', isoN: 516, continent: 'Africa', aliases: ['south west africa', 'namibia republic'] },
  { name: 'Niger', iso3: 'NER', isoN: 562, continent: 'Africa', aliases: ['niger republic', 'nijer'] },
  { name: 'Nigeria', iso3: 'NGA', isoN: 566, continent: 'Africa', aliases: ['nigeria republic', 'nigera', 'niegria'] },
  { name: 'Rwanda', iso3: 'RWA', isoN: 646, continent: 'Africa', aliases: ['ruanda', 'ruwanda'] },
  { name: 'Sao Tome and Principe', iso3: 'STP', isoN: 678, continent: 'Africa', aliases: ['sao tome', 'são tomé and príncipe', 'são tomé e príncipe', 'sao tome & principe'] },
  { name: 'Senegal', iso3: 'SEN', isoN: 686, continent: 'Africa', aliases: ['senegal republic', 'senagal'] },
  { name: 'Seychelles', iso3: 'SYC', isoN: 690, continent: 'Africa', aliases: ['seychelle islands', 'seycheles'] },
  { name: 'Sierra Leone', iso3: 'SLE', isoN: 694, continent: 'Africa', aliases: ['sierraleone', 'sierra leon'] },
  { name: 'Somalia', iso3: 'SOM', isoN: 706, continent: 'Africa', aliases: ['somali', 'somaliya', 'somolia'] },
  { name: 'South Africa', iso3: 'ZAF', isoN: 710, continent: 'Africa', aliases: ['rsa', 's africa', 'south africa republic'] },
  { name: 'South Sudan', iso3: 'SSD', isoN: 728, continent: 'Africa', aliases: ['southsudan', 'south sudan republic'] },
  { name: 'Sudan', iso3: 'SDN', isoN: 729, continent: 'Africa', aliases: ['republic of sudan', 'north sudan'] },
  { name: 'Tanzania', iso3: 'TZA', isoN: 834, continent: 'Africa', aliases: ['tanganyika', 'tanzanea', 'tanzenia'] },
  { name: 'Togo', iso3: 'TGO', isoN: 768, continent: 'Africa', aliases: ['togo republic', 'togolese republic'] },
  { name: 'Tunisia', iso3: 'TUN', isoN: 788, continent: 'Africa', aliases: ['tunisie', 'tunesia', 'tunicia'] },
  { name: 'Uganda', iso3: 'UGA', isoN: 800, continent: 'Africa', aliases: ['uganda republic'] },
  { name: 'Zambia', iso3: 'ZMB', isoN: 894, continent: 'Africa', aliases: ['northern rhodesia', 'zambiа'] },
  { name: 'Zimbabwe', iso3: 'ZWE', isoN: 716, continent: 'Africa', aliases: ['rhodesia', 'zimbabe', 'zimbabwae'] },

  // ─── Asia ─────────────────────────────────────────────────────────────────
  { name: 'Afghanistan', iso3: 'AFG', isoN: 4, continent: 'Asia', aliases: ['afganistan', 'afghnistan', 'afganisthan'] },
  { name: 'Armenia', iso3: 'ARM', isoN: 51, continent: 'Asia', aliases: ['hayastan', 'armenien', 'armenya'] },
  { name: 'Azerbaijan', iso3: 'AZE', isoN: 31, continent: 'Asia', aliases: ['azerbaidjan', 'azerbaycan', 'azerbaijan republic'] },
  { name: 'Bahrain', iso3: 'BHR', isoN: 48, continent: 'Asia', aliases: ['bahrein', 'bahrien'] },
  { name: 'Bangladesh', iso3: 'BGD', isoN: 50, continent: 'Asia', aliases: ['bangla desh', 'banglades', 'bangladash', 'east pakistan'] },
  { name: 'Bhutan', iso3: 'BTN', isoN: 64, continent: 'Asia', aliases: ['druk yul', 'butan', 'bhuthan'] },
  { name: 'Brunei', iso3: 'BRN', isoN: 96, continent: 'Asia', aliases: ['brunei darussalam', 'brunei darussalem'] },
  { name: 'Cambodia', iso3: 'KHM', isoN: 116, continent: 'Asia', aliases: ['kampuchea', 'cambodia kingdom', 'cambioda', 'camboda'] },
  { name: 'China', iso3: 'CHN', isoN: 156, continent: 'Asia', aliases: ["people's republic of china", 'prc', 'zhongguo', 'chine', 'cina'] },
  { name: 'Hong Kong', iso3: 'HKG', isoN: 344, continent: 'Asia', aliases: ['hongkong', 'hk', 'hong kong sar', 'hksar'] },
  { name: 'Macau', iso3: 'MAC', isoN: 446, continent: 'Asia', aliases: ['macao', 'macau sar', 'aomen'] },
  { name: 'Georgia', iso3: 'GEO', isoN: 268, continent: 'Asia', aliases: ['sakartvelo', 'gruziya', 'georgia republic'] },
  { name: 'India', iso3: 'IND', isoN: 356, continent: 'Asia', aliases: ['bharat', 'hindustan', 'indea'] },
  { name: 'Indonesia', iso3: 'IDN', isoN: 360, continent: 'Asia', aliases: ['indonesea', 'indonesia republic', 'indonasia'] },
  { name: 'Iran', iso3: 'IRN', isoN: 364, continent: 'Asia', aliases: ['persia', 'iran republic', 'islamic republic of iran', 'irán'] },
  { name: 'Iraq', iso3: 'IRQ', isoN: 368, continent: 'Asia', aliases: ['irak', 'iraq republic', 'mesopotamia'] },
  { name: 'Israel', iso3: 'ISR', isoN: 376, continent: 'Asia', aliases: ['israil', 'isreal', 'yisrael'] },
  { name: 'Japan', iso3: 'JPN', isoN: 392, continent: 'Asia', aliases: ['nihon', 'nippon', 'japon', 'japón'] },
  { name: 'Jordan', iso3: 'JOR', isoN: 400, continent: 'Asia', aliases: ['hashemite kingdom', 'hashemite kingdom of jordan', 'jordania'] },
  { name: 'Kazakhstan', iso3: 'KAZ', isoN: 398, continent: 'Asia', aliases: ['kazakstan', 'kazahstan', 'qazaqstan'] },
  { name: 'Kuwait', iso3: 'KWT', isoN: 414, continent: 'Asia', aliases: ['koweit', 'kuweit'] },
  { name: 'Kyrgyzstan', iso3: 'KGZ', isoN: 417, continent: 'Asia', aliases: ['kirghizia', 'kyrghyzstan', 'kirgizstan', 'kyrgyz republic'] },
  { name: 'Laos', iso3: 'LAO', isoN: 418, continent: 'Asia', aliases: ['lao', 'lao pdr', 'lao peoples democratic republic'] },
  { name: 'Lebanon', iso3: 'LBN', isoN: 422, continent: 'Asia', aliases: ['liban', 'lebnan', 'libanon'] },
  { name: 'Malaysia', iso3: 'MYS', isoN: 458, continent: 'Asia', aliases: ['malasia', 'malayasia', 'malaisia'] },
  { name: 'Maldives', iso3: 'MDV', isoN: 462, continent: 'Asia', aliases: ['maldive islands', 'maldiv', 'maldivs'] },
  { name: 'Mongolia', iso3: 'MNG', isoN: 496, continent: 'Asia', aliases: ['mongolia republic', 'mongol', 'outer mongolia'] },
  { name: 'Myanmar', iso3: 'MMR', isoN: 104, continent: 'Asia', aliases: ['burma', 'birma', 'myanma', 'myanmar republic'] },
  { name: 'Nepal', iso3: 'NPL', isoN: 524, continent: 'Asia', aliases: ['napel', 'neepal', 'nepal republic'] },
  { name: 'North Korea', iso3: 'PRK', isoN: 408, continent: 'Asia', aliases: ['dprk', 'north corea', 'north koriea', 'democratic peoples republic of korea', 'north korea republic'] },
  { name: 'Oman', iso3: 'OMN', isoN: 512, continent: 'Asia', aliases: ['muscat', 'oman sultanate', 'sultante of oman'] },
  { name: 'Pakistan', iso3: 'PAK', isoN: 586, continent: 'Asia', aliases: ['pakistann', 'pakitan', 'pak'] },
  { name: 'Palestine', iso3: 'PSE', isoN: 275, continent: 'Asia', aliases: ['palestinian territories', 'state of palestine', 'west bank', 'gaza'] },
  { name: 'Philippines', iso3: 'PHL', isoN: 608, continent: 'Asia', aliases: ['pilipinas', 'filipinas', 'phillipines', 'philipines'] },
  { name: 'Qatar', iso3: 'QAT', isoN: 634, continent: 'Asia', aliases: ['katar', 'quatar'] },
  { name: 'Saudi Arabia', iso3: 'SAU', isoN: 682, continent: 'Asia', aliases: ['saudi', 'ksa', 'saudi arabea', 'saudia arabia', 'saudiarabia'] },
  { name: 'Singapore', iso3: 'SGP', isoN: 702, continent: 'Asia', aliases: ['singapor', 'singapur', 'singapour'] },
  { name: 'South Korea', iso3: 'KOR', isoN: 410, continent: 'Asia', aliases: ['korea', 'republic of korea', 'south corea', 'sth korea', 'sth corea'] },
  { name: 'Sri Lanka', iso3: 'LKA', isoN: 144, continent: 'Asia', aliases: ['ceylon', 'srilanka', 'sri lnaka', 'shri lanka'] },
  { name: 'Syria', iso3: 'SYR', isoN: 760, continent: 'Asia', aliases: ['syrian arab republic', 'siria', 'suriya'] },
  { name: 'Taiwan', iso3: 'TWN', isoN: 158, continent: 'Asia', aliases: ['republic of china', 'chinese taipei', 'formosa', 'taiwain'] },
  { name: 'Tajikistan', iso3: 'TJK', isoN: 762, continent: 'Asia', aliases: ['tadzhikistan', 'tadjikistan', 'tajikstan'] },
  { name: 'Thailand', iso3: 'THA', isoN: 764, continent: 'Asia', aliases: ['siam', 'tailand', 'thaialnd'] },
  { name: 'Timor-Leste', iso3: 'TLS', isoN: 626, continent: 'Asia', aliases: ['east timor', 'eastern timor', 'timor leste'] },
  { name: 'Turkmenistan', iso3: 'TKM', isoN: 795, continent: 'Asia', aliases: ['turkmenestan', 'turkmenia', 'turkmeniatan'] },
  { name: 'United Arab Emirates', iso3: 'ARE', isoN: 784, continent: 'Asia', aliases: ['uae', 'emirates', 'arab emirates', 'dubai', 'abu dhabi'] },
  { name: 'Uzbekistan', iso3: 'UZB', isoN: 860, continent: 'Asia', aliases: ['uzbek', 'uzbekystan', 'ozbekiston'] },
  { name: 'Vietnam', iso3: 'VNM', isoN: 704, continent: 'Asia', aliases: ['viet nam', 'vietname', 'viet-nam', 'north vietnam', 'south vietnam'] },
  { name: 'Yemen', iso3: 'YEM', isoN: 887, continent: 'Asia', aliases: ['republic of yemen', 'yeman', 'yemin'] },

  // ─── Europe ───────────────────────────────────────────────────────────────
  { name: 'Albania', iso3: 'ALB', isoN: 8, continent: 'Europe', aliases: ['shqiperi', 'albanie', 'albanea'] },
  { name: 'Andorra', iso3: 'AND', isoN: 20, continent: 'Europe', aliases: ['andorrah', 'principality of andorra'] },
  { name: 'Austria', iso3: 'AUT', isoN: 40, continent: 'Europe', aliases: ['österreich', 'osterreich', 'austrea'] },
  { name: 'Belarus', iso3: 'BLR', isoN: 112, continent: 'Europe', aliases: ['byelorussia', 'belorussia', 'byelarus', 'white russia'] },
  { name: 'Belgium', iso3: 'BEL', isoN: 56, continent: 'Europe', aliases: ['belgique', 'belgien', 'belguim', 'belguim'] },
  { name: 'Bosnia and Herzegovina', iso3: 'BIH', isoN: 70, continent: 'Europe', aliases: ['bosnia', 'bih', 'bosna', 'hercegovina', 'bosnia herzegovina'] },
  { name: 'Bulgaria', iso3: 'BGR', isoN: 100, continent: 'Europe', aliases: ['bulgaria republic', 'bulgarien', 'bolgaria'] },
  { name: 'Croatia', iso3: 'HRV', isoN: 191, continent: 'Europe', aliases: ['hrvatska', 'croacia', 'coatia'] },
  { name: 'Cyprus', iso3: 'CYP', isoN: 196, continent: 'Europe', aliases: ['kypros', 'kibris', 'cypros'] },
  { name: 'Czech Republic', iso3: 'CZE', isoN: 203, continent: 'Europe', aliases: ['czechia', 'czech', 'czech rep', 'czechrepublic', 'cesko', 'česko'] },
  { name: 'Denmark', iso3: 'DNK', isoN: 208, continent: 'Europe', aliases: ['danmark', 'denmarke', 'danemark', 'greenland', 'grønland', 'faroe islands', 'faroes', 'færøerne'] },
  { name: 'Estonia', iso3: 'EST', isoN: 233, continent: 'Europe', aliases: ['eesti', 'estonie', 'esthonia'] },
  { name: 'Finland', iso3: 'FIN', isoN: 246, continent: 'Europe', aliases: ['suomi', 'finlande', 'finnland'] },
  { name: 'France', iso3: 'FRA', isoN: 250, continent: 'Europe', aliases: ['republique francaise', 'french republic', 'frnace', 'frannce', 'french guiana', 'guadeloupe', 'martinique', 'reunion', 'réunion', 'mayotte'] },
  { name: 'Germany', iso3: 'DEU', isoN: 276, continent: 'Europe', aliases: ['deutschland', 'allemagne', 'germeny', 'germay', 'germnay'] },
  { name: 'Greece', iso3: 'GRC', isoN: 300, continent: 'Europe', aliases: ['hellas', 'ellada', 'grece', 'grecia'] },
  { name: 'Hungary', iso3: 'HUN', isoN: 348, continent: 'Europe', aliases: ['magyarország', 'magyarorszag', 'hungaria'] },
  { name: 'Iceland', iso3: 'ISL', isoN: 352, continent: 'Europe', aliases: ['island', 'islande', 'ísland'] },
  { name: 'Ireland', iso3: 'IRL', isoN: 372, continent: 'Europe', aliases: ['eire', 'éire', 'republic of ireland', 'irish republic'] },
  { name: 'Italy', iso3: 'ITA', isoN: 380, continent: 'Europe', aliases: ['italia', 'italie', 'italian republic', 'itlay'] },
  { name: 'Kosovo', iso3: 'XKX', isoN: -1, continent: 'Europe', aliases: ['kosova', 'kosovë', 'republic of kosovo', 'kosowo'] },
  { name: 'Latvia', iso3: 'LVA', isoN: 428, continent: 'Europe', aliases: ['latvija', 'lettonia', 'lettland'] },
  { name: 'Liechtenstein', iso3: 'LIE', isoN: 438, continent: 'Europe', aliases: ['lichtenstein', 'principality of liechtenstein'] },
  { name: 'Lithuania', iso3: 'LTU', isoN: 440, continent: 'Europe', aliases: ['lietuva', 'lituanie', 'lithuainia'] },
  { name: 'Luxembourg', iso3: 'LUX', isoN: 442, continent: 'Europe', aliases: ['luxemburg', 'lëtzebuerg', 'luxembourgh'] },
  { name: 'Malta', iso3: 'MLT', isoN: 470, continent: 'Europe', aliases: ['maltese republic', 'malte'] },
  { name: 'Moldova', iso3: 'MDA', isoN: 498, continent: 'Europe', aliases: ['moldavia', 'republic of moldova', 'moldovа'] },
  { name: 'Monaco', iso3: 'MCO', isoN: 492, continent: 'Europe', aliases: ['principality of monaco', 'monacco'] },
  { name: 'Montenegro', iso3: 'MNE', isoN: 499, continent: 'Europe', aliases: ['crna gora', 'monenegro', 'montenegr'] },
  { name: 'Netherlands', iso3: 'NLD', isoN: 528, continent: 'Europe', aliases: ['holland', 'nederland', 'the netherlands', 'neatherlands', 'netheralnds', 'aruba', 'curacao', 'curaçao'] },
  { name: 'North Macedonia', iso3: 'MKD', isoN: 807, continent: 'Europe', aliases: ['macedonia', 'former yugoslav republic of macedonia', 'fyr macedonia', 'north macedoia', 'makedonia'] },
  { name: 'Norway', iso3: 'NOR', isoN: 578, continent: 'Europe', aliases: ['norge', 'norwegen', 'norweigen', 'norways'] },
  { name: 'Poland', iso3: 'POL', isoN: 616, continent: 'Europe', aliases: ['polska', 'pologne', 'poalnd'] },
  { name: 'Portugal', iso3: 'PRT', isoN: 620, continent: 'Europe', aliases: ['portugual', 'portugall', 'portgual'] },
  { name: 'Romania', iso3: 'ROU', isoN: 642, continent: 'Europe', aliases: ['rumania', 'roumanie', 'roumania', 'romenia'] },
  { name: 'Russia', iso3: 'RUS', isoN: 643, continent: 'Europe', aliases: ['russian federation', 'rossiya', 'russie', 'rusia', 'rusisa'] },
  { name: 'San Marino', iso3: 'SMR', isoN: 674, continent: 'Europe', aliases: ['republic of san marino', 'san marinno'] },
  { name: 'Serbia', iso3: 'SRB', isoN: 688, continent: 'Europe', aliases: ['srbija', 'serbie', 'serbien'] },
  { name: 'Slovakia', iso3: 'SVK', isoN: 703, continent: 'Europe', aliases: ['slovak republic', 'slovensko', 'slovaquia'] },
  { name: 'Slovenia', iso3: 'SVN', isoN: 705, continent: 'Europe', aliases: ['slovenija', 'slovenie', 'sloveniа'] },
  { name: 'Spain', iso3: 'ESP', isoN: 724, continent: 'Europe', aliases: ['españa', 'espana', 'espagne', 'hispania', 'spian'] },
  { name: 'Sweden', iso3: 'SWE', isoN: 752, continent: 'Europe', aliases: ['sverige', 'suède', 'schweden', 'sweeden'] },
  { name: 'Switzerland', iso3: 'CHE', isoN: 756, continent: 'Europe', aliases: ['schweiz', 'suisse', 'svizzera', 'swizterland', 'swizerland'] },
  { name: 'Turkey', iso3: 'TUR', isoN: 792, continent: 'Europe', aliases: ['turkiye', 'türkiye', 'turkia', 'turky'] },
  { name: 'Ukraine', iso3: 'UKR', isoN: 804, continent: 'Europe', aliases: ['ukraina', 'ukrane', 'ukranie'] },
  { name: 'United Kingdom', iso3: 'GBR', isoN: 826, continent: 'Europe', aliases: ['uk', 'britain', 'great britain', 'england', 'gb', 'united kingdom of great britain', 'engalnd', 'scotland', 'wales', 'northern ireland', 'ni'] },
  { name: 'Vatican', iso3: 'VAT', isoN: 336, continent: 'Europe', aliases: ['vatican city', 'holy see', 'vaticano', 'vatikan'] },

  // ─── North & Central America ──────────────────────────────────────────────
  { name: 'Belize', iso3: 'BLZ', isoN: 84, continent: 'North America', aliases: ['british honduras', 'beliz'] },
  { name: 'Canada', iso3: 'CAN', isoN: 124, continent: 'North America', aliases: ['canadа', 'kanada'] },
  { name: 'Costa Rica', iso3: 'CRI', isoN: 188, continent: 'North America', aliases: ['costarica', 'costa rica republic'] },
  { name: 'El Salvador', iso3: 'SLV', isoN: 222, continent: 'North America', aliases: ['salvador', 'el savador', 'el salavador'] },
  { name: 'Guatemala', iso3: 'GTM', isoN: 320, continent: 'North America', aliases: ['guatemale', 'gautemala', 'guatamala'] },
  { name: 'Honduras', iso3: 'HND', isoN: 340, continent: 'North America', aliases: ['honudras', 'hondoras', 'honduars'] },
  { name: 'Mexico', iso3: 'MEX', isoN: 484, continent: 'North America', aliases: ['méxico', 'mejico', 'mexiko', 'mexcio'] },
  { name: 'Nicaragua', iso3: 'NIC', isoN: 558, continent: 'North America', aliases: ['nicarague', 'nicaaragua'] },
  { name: 'Panama', iso3: 'PAN', isoN: 591, continent: 'North America', aliases: ['panana', 'panaма'] },
  { name: 'United States', iso3: 'USA', isoN: 840, continent: 'North America', aliases: ['usa', 'us', 'america', 'united states of america', 'the us', 'the usa', 'us of america', 'puerto rico', 'puerto rico island', 'pr', 'puertro rico'] },

  // ─── South America & Caribbean ────────────────────────────────────────────
  { name: 'Antigua and Barbuda', iso3: 'ATG', isoN: 28, continent: 'South America', aliases: ['antigua', 'antigua & barbuda', 'antiguaand barbuda'] },
  { name: 'Argentina', iso3: 'ARG', isoN: 32, continent: 'South America', aliases: ['argentia', 'argentyna', 'argentian'] },
  { name: 'Bahamas', iso3: 'BHS', isoN: 44, continent: 'South America', aliases: ['the bahamas', 'bahama islands', 'bahammas'] },
  { name: 'Barbados', iso3: 'BRB', isoN: 52, continent: 'South America', aliases: ['barbadoes', 'barbadoss'] },
  { name: 'Bolivia', iso3: 'BOL', isoN: 68, continent: 'South America', aliases: ['bolivea', 'boliviа', 'plurinational state of bolivia'] },
  { name: 'Brazil', iso3: 'BRA', isoN: 76, continent: 'South America', aliases: ['brasil', 'brasill', 'brazile', 'brazill', 'brzil', 'brezil', 'brazi'] },
  { name: 'Chile', iso3: 'CHL', isoN: 152, continent: 'South America', aliases: ['republic of chile', 'chille', 'cile'] },
  { name: 'Colombia', iso3: 'COL', isoN: 170, continent: 'South America', aliases: ['columbia', 'colombea', 'kolumbia'] },
  { name: 'Cuba', iso3: 'CUB', isoN: 192, continent: 'South America', aliases: ['republic of cuba', 'cubа'] },
  { name: 'Dominica', iso3: 'DMA', isoN: 212, continent: 'South America', aliases: ['commonwealth of dominica'] },
  { name: 'Dominican Republic', iso3: 'DOM', isoN: 214, continent: 'South America', aliases: ['dominican rep', 'dr', 'santo domingo', 'republic dominicana', 'republica dominicana'] },
  { name: 'Ecuador', iso3: 'ECU', isoN: 218, continent: 'South America', aliases: ['equador', 'equator', 'equatoor'] },
  { name: 'Grenada', iso3: 'GRD', isoN: 308, continent: 'South America', aliases: ['granadа', 'greneda'] },
  { name: 'Guyana', iso3: 'GUY', isoN: 328, continent: 'South America', aliases: ['british guiana', 'guyana republic', 'guayana'] },
  { name: 'Haiti', iso3: 'HTI', isoN: 332, continent: 'South America', aliases: ['hayti', 'haiiti', 'ayiti'] },
  { name: 'Jamaica', iso3: 'JAM', isoN: 388, continent: 'South America', aliases: ['jamica', 'jamaiка', 'jamaicа'] },
  { name: 'Paraguay', iso3: 'PRY', isoN: 600, continent: 'South America', aliases: ['paraguey', 'paraguy'] },
  { name: 'Peru', iso3: 'PER', isoN: 604, continent: 'South America', aliases: ['perú', 'piru', 'peru republic'] },
  { name: 'Saint Kitts and Nevis', iso3: 'KNA', isoN: 659, continent: 'South America', aliases: ['st kitts', 'st kitts and nevis', 'saint kitts', 'st kitts nevis', 'saint kitts nevis'] },
  { name: 'Saint Lucia', iso3: 'LCA', isoN: 662, continent: 'South America', aliases: ['st lucia', 'sainte lucie', 'st. lucia'] },
  { name: 'Saint Vincent and the Grenadines', iso3: 'VCT', isoN: 670, continent: 'South America', aliases: ['st vincent', 'saint vincent', 'st vincent and grenadines', 'st. vincent'] },
  { name: 'Suriname', iso3: 'SUR', isoN: 740, continent: 'South America', aliases: ['surinam', 'dutch guiana', 'suriname republic'] },
  { name: 'Trinidad and Tobago', iso3: 'TTO', isoN: 780, continent: 'South America', aliases: ['trinidad', 'trinidad & tobago', 'trinidadand tobago'] },
  { name: 'Uruguay', iso3: 'URY', isoN: 858, continent: 'South America', aliases: ['uruguai', 'uruguey', 'oriental republic of uruguay'] },
  { name: 'Venezuela', iso3: 'VEN', isoN: 862, continent: 'South America', aliases: ['venezuala', 'venezueal', 'bolivarian republic of venezuela'] },

  // ─── Oceania ──────────────────────────────────────────────────────────────
  { name: 'Australia', iso3: 'AUS', isoN: 36, continent: 'Oceania', aliases: ['aussie', 'australea', 'austrilia', 'oz'] },
  { name: 'Fiji', iso3: 'FJI', isoN: 242, continent: 'Oceania', aliases: ['republic of fiji', 'fiji islands'] },
  { name: 'Kiribati', iso3: 'KIR', isoN: 296, continent: 'Oceania', aliases: ['kiribas', 'kiribatti', 'republic of kiribati'] },
  { name: 'Marshall Islands', iso3: 'MHL', isoN: 584, continent: 'Oceania', aliases: ['marshall island', 'republic of marshall islands'] },
  { name: 'Micronesia', iso3: 'FSM', isoN: 583, continent: 'Oceania', aliases: ['federated states of micronesia', 'fsm', 'micronesea'] },
  { name: 'Nauru', iso3: 'NRU', isoN: 520, continent: 'Oceania', aliases: ['republic of nauru', 'pleasant island'] },
  { name: 'New Zealand', iso3: 'NZL', isoN: 554, continent: 'Oceania', aliases: ['nz', 'aotearoa', 'new zeland', 'newzealand', 'new zealnd'] },
  { name: 'Palau', iso3: 'PLW', isoN: 585, continent: 'Oceania', aliases: ['republic of palau', 'pelew'] },
  { name: 'Papua New Guinea', iso3: 'PNG', isoN: 598, continent: 'Oceania', aliases: ['png', 'papua guinea', 'papau new guinea', 'papua new guinee'] },
  { name: 'Samoa', iso3: 'WSM', isoN: 882, continent: 'Oceania', aliases: ['western samoa', 'independent state of samoa', 'samoan islands'] },
  { name: 'Solomon Islands', iso3: 'SLB', isoN: 90, continent: 'Oceania', aliases: ['solomon island', 'british solomon islands', 'solomons'] },
  { name: 'Tonga', iso3: 'TON', isoN: 776, continent: 'Oceania', aliases: ['kingdom of tonga', 'friendly islands'] },
  { name: 'Tuvalu', iso3: 'TUV', isoN: 798, continent: 'Oceania', aliases: ['ellice islands', 'tuvalo'] },
  { name: 'Vanuatu', iso3: 'VUT', isoN: 548, continent: 'Oceania', aliases: ['new hebrides', 'vanuatoo', 'vanuatú'] },
];

// Deduplicate by iso3 (in case of accidental duplication)
const seen = new Set<string>();
export const COUNTRIES: Country[] = countries.filter(c => {
  if (seen.has(c.iso3)) return false;
  seen.add(c.iso3);
  return true;
});

// Fast lookup by canonical name (lowercase)
export const COUNTRY_BY_NAME = new Map<string, Country>(
  COUNTRIES.map(c => [c.name.toLowerCase(), c])
);

// Fast lookup by isoN (for map coloring)
export const COUNTRY_BY_ISON = new Map<number, Country>(
  COUNTRIES.filter(c => c.isoN > 0).map(c => [c.isoN, c])
);
